version: "3.8"

services:

  nginx-proxy:
    container_name: nginx-proxy
    hostname: nginx-proxy
    image: jwilder/nginx-proxy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - docker-net

networks:
  docker-net:
    name: docker-net
    external: false
