version: "3.8"

services:

  nginx-proxy:
    container_name: nginx-proxy
    hostname: nginx-proxy
    image: jwilder/nginx-proxy:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-proxy:/etc/nginx/certs
      - nginx-proxy:/etc/nginx/vhost.d
      - nginx-proxy:/usr/share/nginx/html
    networks:
      - docker-net

  letsencrypt:
    container_name: letsencrypt
    hostname: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-proxy:/etc/nginx/certs
      - nginx-proxy:/etc/nginx/vhost.d
      - nginx-proxy:/usr/share/nginx/html
    networks:
      - docker-net

networks:
  docker-net:
    name: docker-net
    external: true

volumes:
  nginx-proxy:
    name: nginx-proxy
    external: false
