version: "3.8"

services:
  rober:
    image: docker.io/brianwolf94/dockers-cluster-rober:latest
    container_name: rober
    hostname: rober
    restart: always
    expose:
      - 80
    networks:
      - docker-net
    volumes:
      - ./data.json:/usr/share/nginx/html/data.json

networks:
  docker-net:
    name: docker-net
    external: true
