name: rober

networks:
  docker-net:
    name: docker-net
    external: true

services:
  rober:
    image: docker.io/brianwolf94/dockers-cluster-rober:20250601
    container_name: rober
    hostname: rober
    restart: always
    expose:
      - 80
    networks:
      - docker-net
    volumes:
      - ./data.json:/usr/share/nginx/html/assets/data.json
