version: "3.8"

services:
    nginx-proxy:
        image: jwilder/nginx-proxy:1.3.1
        container_name: nginx-proxy
        hostname: nginx-proxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - docker-net

networks:
    docker-net:


