version: "3.8"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    hostname: filebrowser
    environment:
      VIRTUAL_HOST: file.lobo.theworkpc.com
      VIRTUAL_PORT: 8080
    expose:
      - 8080
    volumes:
      - /home/brian/volumes/:/data:Z
      - filebrowser:/config
      - filebrowser:/database.db
      - filebrowser:/.filebrowser.json
    networks:
      - docker-net

networks:
  docker-net:
    name: docker-net
    external: true

volumes:
  filebrowser:
    name: filebrowser
    external: false
