version: "3.8"

services:

  sonar:
    image: sonarqube:10.7.0-community
    container_name: sonar
    hostname: sonar
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    expose:
      - 9000
    volumes:
      - sonar:/opt/sonarqube
    networks:
      - docker-net
    depends_on:
      - sonar-postgres

  sonar-postgres:
    image: postgres:15.3
    container_name: sonar-postgres
    hostname: sonar-postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_DB: sonar
      POSTGRES_PASSWORD: sonar
    expose:
      - 5432
    volumes:
      - sonar-postgres:/var/lib/postgresql/data
    networks:
      - docker-net
    healthcheck:
      start_period: 6s

volumes:
  sonar:
    name: sonar
    external: false
  sonar-postgres:
    name: sonar-postgres
    external: false

networks:
  docker-net:
    name: docker-net
    external: true
