name: navidrome

volumes:
  navidrome:
    name: navidrome
    external: false

networks:
  docker-net:
    name: docker-net
    external: true

services:
  navidrome:
    image: deluan/navidrome:0.56.1
    container_name: navidrome
    hostname: navidrome
    restart: always
    expose:
      - 4533
    volumes:
      - navidrome:/data:rw
      - /media/sda/volumes/navidrome:/music:Z
    networks:
      - docker-net

  edit_metadata_songs:
    image: python:3.12-slim
    container_name: edit_metadata_songs
    hostname: edit_metadata_songs
    volumes:
      - ./python/:/home/src/
      - /media/sda/volumes/navidrome:/music:Z
    networks:
      - docker-net
    command: [ "/bin/bash", "-c", "cd /home/src/ && pip3 install -r requirements.txt && python3 script.py /music > edit_metadata_songs.log" ]
