version: "3.8"

services:
  jenkins:
    container_name: jenkins
    hostname: jenkins
    image: jenkins/jenkins:2.414
    restart: always
    user: root
    volumes:
      - jenkins:/var/jenkins_home:rw
    networks:
      - docker-net
    expose:
      - 8080
      - 50000

networks:
  docker-net:
    name: docker-net
    external: true

volumes:
  jenkins:
    name: jenkins
    external: false
