version: "3.8"

services:
  jellyfin:
    container_name: jellyfin
    hostname: jellyfin
    image: linuxserver/jellyfin:10.8.10
    restart: always
    environment:
      VIRTUAL_HOST: series.lobo.theworkpc.com
      VIRTUAL_PORT: 8096
      # JELLYFIN_PublishedServerUrl: series.lobo.theworkpc.com
    volumes:
      - jellyfin:/config
      - jellyfin:/cache
      - /home/brian/volumes/jellyfin:/media:Z
    expose:
      - 8096

networks:
  docker-net:
    name: docker-net
    external: true

volumes:
  jellyfin:
    name: jellyfin
    external: false
