version: "3.8"

services:
    portainer:
        image: portainer/portainer:linux-amd64-2.0.1
        container_name: portainer
        hostname: portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - portainer:/data portainer/portainer:rw
        networks:
            - docker-net
        ports:
            - 9000:9000
            - 8000:8000
        command: -H unix:///var/run/docker.sock

networks:
    docker-net:
        name: docker-net

volumes:
    portainer:
        name: portainer
