name: nginx-proxy-manager

volumes:
  nginx-proxy-manager:
    name: nginx-proxy-manager
    external: false

networks:
  docker-net:
    name: docker-net
    external: true

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.12.1
    container_name: nginx-proxy-manager
    hostname: nginx-proxy-manager
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - nginx-proxy-manager:/data
      - nginx-proxy-manager:/etc/letsencrypt
    networks:
      - docker-net
