version: "3.8"

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - 80:80
      - 81:81
      - 443:443
    networks:
      - docker-net
    volumes:
      - nginx-proxy-manager:/data
      - nginx-proxy-manager:/etc/letsencrypt

networks:
  docker-net:
    name: docker-net
    external: true

volumes:
  nginx-proxy-manager:
    name: nginx-proxy-manager
    external: false
