name: docker-sync

on:
  push:
    branches:
      - main
      
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
    - name: connect with docker-sync
      run: curl pc.brianlobo.theworkpc.com:5000/api/v1/sync/
  
